name       : compiz-bcop
version    : 0.8.16
release    : 1
source     :
    - https://gitlab.com/compiz/compiz-bcop/-/archive/v0.8.16/compiz-bcop-v0.8.16.tar.bz2 : 0695a46f02f6238bf9a478124a562f71da32354b83c6e5c7ec97cfd49d9882d4
license    : GPL-2.0-or-later
component  : desktop.mate
summary    : compiz bcop
description: |
    compiz bcop
builddeps  :
    - pkgconfig(libxslt)
setup      : |
    %reconfigure
build      : |
    %make
install    : |
    %make_install
