name       : compiz-bcop
version    : 0.8.18
release    : 2
source     :
    - https://gitlab.com/compiz/compiz-bcop/-/archive/v0.8.18/compiz-bcop-v0.8.18.tar.bz2 : 1bc027d683ba3694aae0664d341379cb29fd721d4761fe45c1c185ee0d46d255
license    : GPL-2.0-or-later
component  : desktop.mate
summary    : compiz bcop
description: |
    compiz bcop
builddeps  :
    - pkgconfig(libxslt)
setup      : |
    %reconfigure
build      : |
    %make
install    : |
    %make_install
